version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${ECOMMERCE_DB}
      POSTGRES_USER: ${FOXECOMMERCE_USER}
      POSTGRES_PASSWORD: ${FOXECOMMERCE_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - ecommerce_network

  web:
    build: .
    command: >
      bash -c "
      ./scripts/wait_for_db.sh
      && python ecommerce/manage.py migrate --noinput
      && python ecommerce/manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - ecommerce_network

volumes:
  postgres_data:

networks:
  ecommerce_network:
